# Generated by Django 4.0.3 on 2023-03-24 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_conference_main_temperature_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conference',
            old_name='main_temperature',
            new_name='main_weather',
        ),
    ]
